--
-- Created by IntelliJ IDEA.
-- User: Gaming
-- Date: 7/26/2014
-- Time: 9:24 PM
-- To change this template use File | Settings | File Templates.
--
self.tWhatHappenedFormDef = {
    AnchorOffsets = { 73, 221, 688, 470 },
    RelativeToClient = true,
    Font = "CRB_Interface14_O",
    BGColor = "UI_WindowBGDefault",
    TextColor = "UI_WindowTextDefault",
    Template = "Holo_Background_General",
    Name = "WhatHappenedForm",
    Border = true,
    Picture = true,
    SwallowMouseClicks = true,
    Moveable = true,
    Escapable = true,
    UseTemplateBG = true,
    NoClip = true,
    Children = {
        {
            AnchorOffsets = { 516, 200, 585, 224 },
            Class = "Button",
            Base = "CRB_UIKitSprites:btn_square_LARGE_Red",
            Font = "DefaultButton",
            ButtonType = "PushButton",
            DT_VCENTER = true,
            DT_CENTER = true,
            BGColor = "UI_BtnBGDefault",
            TextColor = "UI_BtnTextDefault",
            NormalTextColor = "UI_BtnTextDefault",
            PressedTextColor = "UI_BtnTextDefault",
            FlybyTextColor = "UI_BtnTextDefault",
            PressedFlybyTextColor = "UI_BtnTextDefault",
            DisabledTextColor = "UI_BtnTextDefault",
            Name = "btnClose",
            TextId = "CRB_Close",
            Events = {
                ButtonSignal = "OnClose",
            },
        },
        {
            AnchorOffsets = { 0, 24, 490, 235 },
            Class = "MLWindow",
            RelativeToClient = true,
            BGColor = "UI_WindowBGDefault",
            TextColor = "UI_WindowTextDefault",
            Template = "Holo_ScrollList",
            Name = "CombatText",
            Border = true,
            VScroll = true,
            UseTemplateBG = true,
            UseParentOpacity = true,
        },
        {
            AnchorOffsets = { -10, -9, 498, 26 },
            Class = "EditBox",
            RelativeToClient = true,
            Font = "CRB_Interface14_BBO",
            Text = "WTF Happened!!",
            BGColor = "UI_WindowBGDefault",
            TextColor = "UI_WindowTextDefault",
            Name = "Title",
            DT_VCENTER = true,
            DT_CENTER = true,
            ReadOnly = true,
            SizeToFit = false,
            Password = false,
            IgnoreMouse = true,
        },
        {
            AnchorOffsets = { 519, 39, 585, 56 },
            Class = "Button",
            Base = "CRB_Basekit:kitBtn_ScrollHolo_HorzBarLarge",
            Font = "CRB_Interface9_BBO",
            ButtonType = "PushButton",
            DT_VCENTER = true,
            DT_CENTER = true,
            NormalTextColor = "UI_BtnTextDefault",
            PressedTextColor = "UI_BtnTextDefault",
            FlybyTextColor = "UI_BtnTextDefault",
            PressedFlybyTextColor = "UI_BtnTextDefault",
            DisabledTextColor = "UI_BtnTextDefault",
            Name = "btnConfig",
            Template = "Tooltip",
            Text = "Config",
            UseTemplateBG = true,
            Picture = true,
            Events = {
                ButtonSignal = "OnConfig",
            },
        },
    },
}
self.tConfigFormDef = {
    AnchorOffsets = { 162, 165, 420, 347 },
    RelativeToClient = true,
    BGColor = "UI_WindowBGDefault",
    TextColor = "UI_WindowTextDefault",
    Template = "Holo_Background_General",
    Name = "ConfigForm",
    Border = true,
    Picture = true,
    SwallowMouseClicks = true,
    Moveable = true,
    Escapable = true,
    Overlapped = true,
    UseTemplateBG = true,
    Children = {
        {
            AnchorOffsets = { -8, -8, 248, 16 },
            RelativeToClient = true,
            Font = "CRB_Interface12_BBO",
            BGColor = "UI_WindowBGDefault",
            TextColor = "UI_WindowTextDefault",
            Name = "Window",
            TextId = "CRB_Configure",
            DT_CENTER = true,
            DT_VCENTER = true,
        },
        {
            AnchorOffsets = { 5, 26, 82, 43 },
            Class = "EditBox",
            RelativeToClient = true,
            Text = "Raid Channel",
            BGColor = "UI_WindowBGDefault",
            TextColor = "UI_WindowTextDefault",
            Name = "EditBox",
            ReadOnly = true,
            SizeToFit = true,
        },
        {
            AnchorOffsets = { 78, 19, 223, 48 },
            Class = "EditBox",
            RelativeToClient = true,
            BGColor = "UI_WindowBGDefault",
            TextColor = "UI_WindowTextDefault",
            Template = "GreyBevInnerFrame",
            Name = "RaidChannel",
            Border = true,
            UseTemplateBG = true,
            DefaultTarget = false,
            DT_CENTER = true,
            DT_VCENTER = true,
        },
        {
            AnchorOffsets = { 66, 124, 187, 162 },
            Class = "Button",
            Base = "BK3:btnHolo_Blue_Small",
            Font = "DefaultButton",
            ButtonType = "PushButton",
            DT_VCENTER = true,
            DT_CENTER = true,
            BGColor = "UI_BtnBGDefault",
            TextColor = "UI_BtnTextDefault",
            NormalTextColor = "UI_BtnTextDefault",
            PressedTextColor = "UI_BtnTextDefault",
            FlybyTextColor = "UI_BtnTextDefault",
            PressedFlybyTextColor = "UI_BtnTextDefault",
            DisabledTextColor = "UI_BtnTextDefault",
            Name = "btnSave",
            TextId = "CRB_Save",
            Border = true,
            UseWindowTextColor = false,
            UseTemplateBG = true,
            Picture = true,
            RelativeToClient = true,
            Events = {
                ButtonSignal = "OnConfigSave",
            },
        },
        {
            AnchorOffsets = { 37, 90, 232, 119 },
            Class = "Button",
            Base = "BK3:btnHolo_Radio_Big",
            Font = "DefaultButton",
            ButtonType = "Check",
            DT_VCENTER = true,
            DT_CENTER = true,
            BGColor = "UI_BtnBGDefault",
            TextColor = "UI_BtnTextDefault",
            NormalTextColor = "UI_BtnTextDefault",
            PressedTextColor = "UI_BtnTextDefault",
            FlybyTextColor = "UI_BtnTextDefault",
            PressedFlybyTextColor = "UI_BtnTextDefault",
            DisabledTextColor = "UI_BtnTextDefault",
            Name = "chkRaidLeader",
            DrawAsCheckbox = true,
            Template = "CRB_Default",
            UseWindowTextColor = true,
            Text = "Raid Leader Mode",
            UseTemplateBG = true,
            GlobalRadioGroup = "",
            Events = {
                ButtonSignal = "YourFunctionName",
            },
        },
        {
            AnchorOffsets = { 2, 51, 234, 95 },
            RelativeToClient = true,
            Text = "Raid Leader Mode - You will recieve reports from others in the same channel.",
            BGColor = "UI_WindowBGDefault",
            TextColor = "UI_WindowTextDefault",
            Name = "Window1",
            DT_CENTER = true,
            DT_WORDBREAK = true,
        },
    },
}
self.tRaidLeaderFormDef = {
    AnchorOffsets = { 93, 90, 685, 337 },
    RelativeToClient = true,
    BGColor = "UI_WindowBGDefault",
    TextColor = "UI_WindowTextDefault",
    Template = "Holo_Background_Datachron",
    Name = "RaidLeaderForm",
    Border = true,
    Picture = true,
    SwallowMouseClicks = true,
    Moveable = true,
    Overlapped = true,
    Children = {
        {
            AnchorOffsets = { 10, 35, 154, 234 },
            RelativeToClient = true,
            BGColor = "UI_WindowBGDefault",
            TextColor = "UI_WindowTextDefault",
            Template = "CRB_HologramFramedThin",
            Name = "RecipientList",
            Border = true,
            IgnoreMouse = true,
            UseTemplateBG = true,
        },
        {
            AnchorOffsets = { 10, 10, 152, 32 },
            RelativeToClient = true,
            Font = "CRB_Interface11_BBO",
            Text = "Recipient List",
            BGColor = "UI_WindowBGDefault",
            TextColor = "UI_WindowTextDefault",
            Name = "lblRecipientList",
            DT_CENTER = true,
            DT_VCENTER = true,
        },
        {
            AnchorOffsets = { 158, 35, 511, 235 },
            RelativeToClient = true,
            BGColor = "UI_WindowBGDefault",
            TextColor = "UI_WindowTextDefault",
            Template = "CRB_HologramFramedThin",
            Name = "PlayerCombatText",
            Border = true,
            IgnoreMouse = true,
            Picture = true,
            UseTemplateBG = true,
        },
        {
            AnchorOffsets = { 176, 10, 503, 36 },
            RelativeToClient = true,
            Font = "CRB_Interface11_BBO",
            Text = "WTF, Where you thinking??",
            BGColor = "UI_WindowBGDefault",
            TextColor = "UI_WindowTextDefault",
            Name = "lblWtf",
            DT_CENTER = true,
            DT_VCENTER = true,
        },
        {
            AnchorOffsets = { 519, 39, 585, 56 },
            Class = "Button",
            Base = "CRB_Basekit:kitBtn_ScrollHolo_HorzBarLarge",
            Font = "CRB_Interface9_BBO",
            ButtonType = "PushButton",
            DT_VCENTER = true,
            DT_CENTER = true,
            NormalTextColor = "UI_BtnTextDefault",
            PressedTextColor = "UI_BtnTextDefault",
            FlybyTextColor = "UI_BtnTextDefault",
            PressedFlybyTextColor = "UI_BtnTextDefault",
            DisabledTextColor = "UI_BtnTextDefault",
            Name = "btnConfig",
            Template = "Tooltip",
            Text = "Config",
            UseTemplateBG = true,
            Picture = true,
            Events = {
                ButtonSignal = "OnConfig",
            },
        },
        {
            AnchorOffsets = { 516, 200, 585, 224 },
            Class = "Button",
            Base = "CRB_UIKitSprites:btn_square_LARGE_Red",
            Font = "DefaultButton",
            ButtonType = "PushButton",
            DT_VCENTER = true,
            DT_CENTER = true,
            BGColor = "UI_BtnBGDefault",
            TextColor = "UI_BtnTextDefault",
            NormalTextColor = "UI_BtnTextDefault",
            PressedTextColor = "UI_BtnTextDefault",
            FlybyTextColor = "UI_BtnTextDefault",
            PressedFlybyTextColor = "UI_BtnTextDefault",
            DisabledTextColor = "UI_BtnTextDefault",
            Name = "btnClose",
            TextId = "CRB_Close",
            Events = {
                ButtonSignal = "OnClose",
            },
        },
    },
}
self.tPlayerNameClickable ={
    AnchorOffsets = { 3, 2, 123, 25 },
    RelativeToClient = true,
    Font = "CRB_Interface10_BBO",
    BGColor = "UI_WindowBGDefault",
    TextColor = "UI_WindowTextDefault",
    Name = "PlayerNameClickable",
    TextId = "CRB_Player_Name",
    DT_CENTER = true,
    DT_VCENTER = true,
    Events = {
        MouseButtonUp = "OnClickGetReport",
    },

}

